### ISSUE TITLE
Can't see UI

### ISSUE THREAD

**Issue by lordvague** [mattsemar/dsp-bulldozer#10]
I just installed the latest version of the mod but its doesn't make a visible UI.  Is there a button I have to press?  Couldn't find this in the instructions/version dialog.

**Comment by mattsemar** [comment]
Did you look in the foundation menu?

**Comment by lordvague** [comment]
Ah I see it now.  If you select foundations from your inventory it normally opens the foundation menu.  It is not visible at this point.  It only seems to become visible in the UI if I select the foundations by pressing 9.  Maybe you can add an instruction to the relavent pages that you need to press 9 to get it to work.

**Comment by lordvague** [comment]
https://i.imgur.com/5Hl5MnP.jpg

Thanks for your help!  Cheers!

**Comment by mattsemar** [comment]
Ah, interesting, I hadn't thought about using foundation from inventory. I added some screen shots to the readme https://dsp.thunderstore.io/package/Semar/Bulldozer
