### ISSUE TITLE
Capsule landing

### ISSUE THREAD

**Issue by FreddyAz** [mattsemar/dsp-bulldozer#12]
Was gonna try get the new achievement ''Memento!''
'Don't dismantle the landing capsule before completing the game.'
But using the mod deletes the landing capsule.

Edit: not the mod but just adding foundations removes it.

Anyways love the mod not gonna start over for it <3

**Comment by mattsemar** [comment]
Wow, so sorry I missed this. I was focused on getting my other mod released and I totally didn't see it. I also didn't realize that the capsule was classified as vegetation by the game.

At any rate, this is resolved in version 1.0.24. 

Thanks for the bug report.
