### ISSUE TITLE
Some features dont work with galactic scale larger planets

### ISSUE THREAD

**Issue by zdauterive** [mattsemar/dsp-bulldozer#17]
For larger planets that typically come with the galactic scale mod, some of the bulldoze features dont work, such as pole painting and sector painting. The meridian painting also gets messed up.

**Comment by mattsemar** [comment]
Please try this again. Should be much improved with version 1.1.4

**Comment by mattsemar** [comment]
Ok, I'm going to close this one, but please open another ticket if you run into problems
