### ISSUE TITLE
Guide Lines not matching Foundation Type

### ISSUE THREAD

**Issue by PiggyWhiskey** [mattsemar/dsp-bulldozer#19]
The guide lines don't match the 'Foundation Decoration Mode' setting resulting in different type of coloured foundations.

![image](https://user-images.githubusercontent.com/9373995/163122228-eebc8ec5-bad6-4000-8b49-9526dd40959e.png)

Is it possible to get this to match the setting?

**Comment by mattsemar** [comment]
I changed this, but just to be clear if foundation decoration mode is Clear it will fallback to `brushType: 1`. Same thing if decoration mode is `Tool` and you have the Clear option selected in toolbar. Let me know if the latest version doesn't work like you expect.

**Comment by PiggyWhiskey** [comment]
It works perfectly. Thank you
