### ISSUE TITLE
[Bug] height map update

### ISSUE THREAD

**Issue by AlienXtream** [mattsemar/dsp-bulldozer#2]
the foundations place but the (raised) areas height map does not appear to update.

**Comment by AlienXtream** [comment]
note, using GS2. may be related to that mod being installed too.

**Comment by mattsemar** [comment]
I'm not sure I understand. Can you give me some more information on what you mean by heightmap?

**Comment by marr75** [comment]
Pretty sure this is related to Galactic Scale 2, as the reporter suggests. The other mathematical assumptions don't hold true for GS2, either. On planets with larger radii than the standard size, I ended up with odd striping of colors. Looking at the code, it looks like the assumed relationship between lat, long, and foundations doesn't hold true on GS2 planets.

GS2 compatibility would be really nice (there are HUGE planets that will give you carpal tunnel to pave 100 tiles at a time) but I understand the complexities involved.

**Comment by mattsemar** [comment]
Ok, I'll take a look at that plugin then

**Comment by mattsemar** [comment]
How big a planet should I be looking at? I just tried one with a radius of 470 and it seemed to work ok. I do see the issue with the stripes having missing spots (working on that part), but all the terrain is the same height.

**Comment by mattsemar** [comment]
I believe this should be resolved now, but if not, please let me know
