### ISSUE TITLE
The newest patch has added buttons over the bulldozer buttons, making them inaccessible

### ISSUE THREAD

**Issue by Umbrasong** [mattsemar/dsp-bulldozer#21]
Version 0.9.26.12913 (I think, that's the most recent patch notes at any rate) in a sandbox game
![image](https://user-images.githubusercontent.com/12302653/174207325-f9cb6618-c7cc-4ad0-bdbf-3387477bd9d5.png)

**Comment by mattsemar** [comment]
Ok, thanks

**Comment by mattsemar** [comment]
This should be fully resolved version 1.1.7
