### ISSUE TITLE
[Suggestion] Various "modes"/presets

### ISSUE THREAD

**Issue by AlienXtream** [mattsemar/dsp-bulldozer#3]
some modes or preset options for foundation colour placement would be nice. 
examples:
Plain Flatten (no cement, Cement type 1 or 2)
Tropic Lines
Segments
Longitudinal

edit: some compat with GS2 would also be nice. (like, instead of using a fixed pattern having it calculate based off the size of the planet)

**Comment by mattsemar** [comment]
I feel like most of this is covered now. Please open a new issue with anything that isn't covered by the recent updates
