### ISSUE TITLE
[Suggestion] Bury toggle

### ISSUE THREAD

**Issue by AlienXtream** [mattsemar/dsp-bulldozer#4]
independent toggle option for un/burying ores (i.e bury all, bury none, keep current state)

**Comment by mattsemar** [comment]
This should already work. It's based off of whatever the build tool bury option you have selected is, though

**Comment by AlienXtream** [comment]
i know. i meant one independent of that setting. in most cases you are going to want to leave any veins as they are (be them buried or not). if you buried some and left some exposed the bulldozer tool will just (un)bury then all. having a 3rd option to not change the state of the veins and leave them as their individual state would be better default behavior (and honestly should be a 3rd vanilla option imo)

**Comment by mattsemar** [comment]
Re-opening, might be able to do some of this

**Comment by mattsemar** [comment]
I don't think there is a way to do the "keep current state" part, but for the other 2 I added config options
